import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'
import FilterContainer from '../components/layouts/home/FilterContainer'
import HomePageMainLayout from '../components/layouts/home/HomePageMainLayout'
import PokemonCardLink from '../components/PokemonCardLink'
import PokemonGridList from '../components/PokemonGridList'
import { getManyPokemons, getPokemon } from '../lib/api'
import { ApiPokemon } from '../lib/types'
import { Pokemon } from '../types/api'
import Colorthief, { Color } from 'colorthief'
import Header from '@components/layouts/shared/Header'

interface HomePageProps {
  pokemons: Pokemon[]
}

const Home: NextPage<HomePageProps> = ({ pokemons }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageMainLayout>
        <Header appName={process.env.APP_NAME as string} />
        <FilterContainer></FilterContainer>
        <div>
          <PokemonGridList>
            <Fragment>
              {pokemons.map((p) => (
                <PokemonCardLink
                  key={p.name}
                  pokemonName={p.name}
                  id={p.name}
                  types={[]}
                  dominantColor={p.dominantColor}
                  sprites={p.sprites}
                />
              ))}
            </Fragment>
          </PokemonGridList>
        </div>
      </HomePageMainLayout>
    </>
  )
}

const fetchPokemonMetadadata = async (
  pokemon: ApiPokemon,
  colorFunc: (str: string, quality: number) => Promise<Color>,
): Promise<Pokemon> => {
  const { sprites, ...rest } = await getPokemon(pokemon.name)
  const pokemonDominantColor = await colorFunc(sprites.front_default, 50)

  return {
    ...rest,
    dominantColor: pokemonDominantColor,
    sprites,
  }
}

export const getServerSideProps: GetServerSideProps = async () => {
  const pokemons = await getManyPokemons()

  const pokemonsWithColors = await Promise.all(
    pokemons.data.results.map(async (p: ApiPokemon) =>
      fetchPokemonMetadadata(p, Colorthief.getColor),
    ),
  )

  return {
    props: {
      pokemons: pokemonsWithColors,
    },
  }
}

export default Home
