import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import FilterContainer from "../components/layouts/home/FilterContainer";
import HomePageMainLayout from "../components/layouts/home/HomePageMainLayout";
import PokemonCardLink from "../components/PokemonCardLink";
import PokemonGridList from "../components/PokemonGridList";
import { getManyPokemons } from "../lib/api";
import { Pokemon } from "../types/api";

interface HomePageProps {
  pokemons: Pokemon[];
}

const Home: NextPage<HomePageProps> = ({ pokemons }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageMainLayout>
        <header>
          <div>
            <Image src="/logo.svg" width={32} height={32} />
          </div>
        </header>

        <FilterContainer></FilterContainer>

        <div>
          <PokemonGridList>
            <Fragment>
              {pokemons.map((p) => (
                <PokemonCardLink
                  key={p.name}
                  pokemonName={p.name}
                  id={p.name}
                  types={[]}
                />
              ))}
            </Fragment>
          </PokemonGridList>
        </div>
      </HomePageMainLayout>
    </div>
  );
};

export const getServerSideProps = async () => {
  const pokemons = await getManyPokemons();

  return {
    props: {
      pokemons: pokemons.data.results,
    },
  };
};

export default Home;
