name: validation
on: [push]
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn install
      - run: yarn build
      - run: yarn prettier
      - run: yarn lint
      - run: yarn test --passWithNoTests
